# Generated by Django 5.1.7 on 2025-03-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('category', models.CharField(blank=True, choices=[('Wedding', 'WEDDING'), ('Birthday', 'BIRTHDAY'), ('Dessert', 'DESSERT'), ('Graduation', 'GRADUATION')], max_length=100, null=True)),
            ],
        ),
    ]
