# Generated by Django 5.1.7 on 2025-03-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teocakes', '0008_alter_cake_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
