# Generated by Django 5.1.7 on 2025-03-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teocakes', '0010_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
