# Generated by Django 5.1.7 on 2025-03-31 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teocakes', '0014_rename_ref_transaction_tx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
