# Generated by Django 5.1.7 on 2025-05-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teocakes', '0015_alter_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='is_latest',
            field=models.BooleanField(default=False),
        ),
    ]
