# Generated by Django 5.1.7 on 2025-05-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teocakes', '0016_cake_is_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='is_bestselling',
            field=models.BooleanField(default=False),
        ),
    ]
