# Generated by Django 5.1.7 on 2025-04-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('cake recipes and baking tips', 'CAKE RECIPES AND BAKING TIPS'), ('celebration ideas', 'CELEBRATION IDEAS'), ('behind the scenes', 'BEHIND THE SCENES'), ('cake design trends', 'CAKE DESIGN TRENDS'), ('customer stories and testimonials', 'CUSTOMER STORIES AND TESIMONIALS'), ('seasonal and holiday specials', 'SEASONAL AND HOLIDAY SPECIALS')], max_length=100, null=True)),
            ],
        ),
    ]
