# Generated by Django 5.1.7 on 2025-05-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
